# -*- coding: utf-8 -*-
"""exercicio_c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FhLRCUETzQHHXEQo4Tgl01-95C2ferS-
"""

from google.colab.patches import cv2_imshow
import cv2
import numpy as np

# Load the image
imagem = cv2.imread('/content/5.jpg',)

verde = (0, 255, 0)
vermelho = (0, 0, 255)

print(imagem.shape[0])
print(imagem.shape[1])
print(imagem.shape[2])

cv2.rectangle(imagem, (780, 390), (1150,700), verde, 3)
fonte = cv2.FONT_HERSHEY_COMPLEX
cv2.putText(imagem, "Capacete", (620, 430), fonte, 1,(verde), 2, cv2. LINE_AA)
cv2.rectangle(imagem, (930, 590), (1080,730), verde, 3)
cv2.putText(imagem, "oculos", (1080, 740), fonte, 1,(verde), 2, cv2. LINE_AA)
cv2.rectangle(imagem, (800, 1250), (950,970), verde, 3)
cv2.putText(imagem, "Radio", (700, 1150), fonte, 1,(verde), 2, cv2. LINE_AA)
cv2.rectangle(imagem, (1050, 1370), (1250,1180), vermelho, 3)
cv2.putText(imagem, "sem luva", (1070, 1430), fonte, 2,(vermelho), 2, cv2. LINE_AA)
cv2.rectangle(imagem, (1610, 1280), (1450,1120), vermelho, 3)
cv2.putText(imagem, "sem luva", (1430, 1100), fonte, 2,(vermelho), 2, cv2. LINE_AA)

cv2_imshow(imagem)
cv2.imwrite("exercicio_c.jpg", imagem)