# -*- coding: utf-8 -*-
"""exercicio_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xQN0U-6rX2WNL1xtqm6SqxlWadYBY5_Y
"""

from google.colab.patches import cv2_imshow
import cv2
import numpy as np

imagem = cv2.imread("/content/3.jpg")

verde = (0, 255, 0)
vermelho = (0, 0, 255)

cv2.rectangle(imagem, (1220, 925), (1500, 1367), vermelho, 3)
fonte = cv2.FONT_HERSHEY_COMPLEX
cv2.putText(imagem, "Gato", (1320, 890), fonte, 1,(vermelho), 2, cv2. LINE_AA)
cv2.rectangle(imagem, (1525, 825), (1955, 1367), verde, 3)
cv2.putText(imagem, "Cachorro", (1530, 815), fonte, 1,(verde), 2, cv2. LINE_AA)

print(imagem.shape[0])
print(imagem.shape[1])
print(imagem.shape[2])



cv2_imshow(imagem)
cv2.imwrite("exercicio_b.jpg", imagem)