# -*- coding: utf-8 -*-
"""revisao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d9t_u7Wk1YB6o8ioCj0KXMYULMEPptpE
"""

x = 10
print(x)

x = [1, 2, 3, 4, 5]
x
x.append(11)
x

x.pop()

x

x[:3]

x[::-1]