# -*- coding: utf-8 -*-
"""saida_dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KdSqB6l4ug8OkuXpygAnSdS85eAHuD4f
"""

print("Bom dia", end= " ")
print("Boa Noite")

# int = %d
# float = %f
# str = %s
x = "maria"
y = 19
print("%s tem %d anos" % (x, y))

x: int; y: int
x = 10
y = 20
print(x)
print(y)

x: float
x = 2.3456
print("{:.2f}".format(x))

from re import M
idade: int
salario : float
nome: str
sexo: str

idade = 38
salario = 5288.00
nome = "Humberto da Silva Lucas"
sexo = "M"

print(f"O funcionario {nome}, sexo {sexo}, ganha R${salario:.2f} e tem {idade} anos.")
#exemplo placeholder
print("O funcionario {:s}, sexo {:s}, ganha R${:.2f} e tem {:d} anos.".format(nome, sexo, salario, idade))